### ISSUE TITLE
Remove all references to "Moby"

### ISSUE THREAD

**Issue by ManoMarks** [spara/atsea#20]
We want to avoid brand confusion, so we'll need something else. Maybe just "artshop"

**Comment by spara** [comment]
let's decide on a name first, it takes some time chasing down all the references in the code and changing them

**Comment by amirmc** [comment]
Gordon's Art Shop?

**Comment by amirmc** [comment]
I see the repo's been renamed to `atsea` (https://github.com/spara/atsea/commit/a4196e82e7a478b784d8774ae9026bc8d6022086)

A quick search shows there are only a few files left that mention `Moby`, in form of `MobyArtShop-0.0.1-SNAPSHOT.jar`.
