### ISSUE TITLE
can we make /atsea be / ?

### ISSUE THREAD

**Issue by nathanleclaire** [spara/atsea#63]
That way when we want to visit the site we'd just go to atseashop.com 

cc @ManoMarks @spara

**Comment by spara** [comment]
yes, but check with @jessvalarezo on how it will impact the client

**Comment by jessvalarezo** [comment]
@nathanleclaire sure! I'll just change the base URL.

**Comment by nathanleclaire** [comment]
er, i guess it might be meant to be `/` is the index.html and the javascript calls `/atsea`?

**Comment by nathanleclaire** [comment]
just want to hit the front page when we go to `/`
