### ISSUE TITLE
wrong "compose" caption for artwork

### ISSUE THREAD

**Issue by gdevillele** [spara/atsea#81]
This drawing does not represent compose, but the entire docker toolset we had back in 2014.
It's kind of a detail but I am mentioning it.

<img width="300" alt="screen shot 2017-04-16 at 3 12 10 pm" src="https://cloud.githubusercontent.com/assets/939999/25074062/5b3242c0-22b9-11e7-8f2b-472396ed758f.png">

**Comment by ManoMarks** [comment]
Fixed, thanks meant to change this
